//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppeInnlevering1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avgang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avgang()
        {
            this.Billets = new HashSet<Billet>();
            this.Billets1 = new HashSet<Billet>();
            this.Billets2 = new HashSet<Billet>();
        }
    
        public int AvgangId { get; set; }
        public System.TimeSpan Tid { get; set; }
        public Nullable<int> Stasjon_StasjonId { get; set; }
        public Nullable<int> Tog_TogId { get; set; }
    
        public virtual Stasjon Stasjon { get; set; }
        public virtual Tog Tog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billet> Billets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billet> Billets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billet> Billets2 { get; set; }
    }
}
