//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppeInnlevering1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billet
    {
        public int BilletId { get; set; }
        public string Type { get; set; }
        public System.DateTime Datokjop { get; set; }
        public int Pris { get; set; }
        public Nullable<int> fra_AvgangId { get; set; }
        public Nullable<int> Til_AvgangId { get; set; }
        public Nullable<int> Avgang_AvgangId { get; set; }
    
        public virtual Avgang Avgang { get; set; }
        public virtual Avgang Avgang1 { get; set; }
        public virtual Avgang Avgang2 { get; set; }
    }
}
