//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppeInnlevering1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class togDatabaseEntities4 : DbContext
    {
        public togDatabaseEntities4()
            : base("name=togDatabaseEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avgang> Avgangs { get; set; }
        public virtual DbSet<Billet> Billets { get; set; }
        public virtual DbSet<Stasjon> Stasjons { get; set; }
        public virtual DbSet<Tog> Togs { get; set; }
    }
}
